exe_tableau: CSVParser.o #tableau.o
	g++ -o exe_tableau CSVParser.o -std=c++11 -Wall -Wextra -DNDEBUG -v

CSVParser.cpp: CSVParser.o
g++ -c CSVParser.cpp -o CSVParser.o -Wall -std=c++11 -I /Users/quentinclayssen/Desktop/Cours/C/project/project_c_sinoquet/include/boost_1_68_0


g++ CSVParserantoine.cpp -o mainantoine -Wall -std=c++11 -I /Users/quentinclayssen/Desktop/Cours/C/project/project_c_sinoquet/include/boost_1_68_0
#tableau.o: tableau.cpp
#	g++ -o tableau.o -c tableau.cpp -Wall -v -std=c++11 -I /Users/quentinclayssen/Desktop/Cours/C/project/project_c_sinoquet/include/boost_1_68_0

autorise:
	chmod exe_tableau u+x
