exe_tableau: tableau.o
	g++ -o exe_tableau tableau.o -std=c++11 -Wall -Wextra -DNDEBUG -v

tableau.o: tableau.cpp
	g++ -o tableau.o -c tableau.cpp -Wall -v -std=c++11 -I /Users/quentinclayssen/Desktop/Cours/C/project/project_c_sinoquet/include/boost_1_68_0

autorise:
	chmod exe_tableau u+x
