Laptop:
g++ CSVParser.cpp -o main -Wall -std=c++11 -I/home/osboxes/Documents/ProjetSinoquet/project_c_sinoquet/include/boost_1_68_0
Fix:
g++ CSVParser.cpp -o main -Wall -std=c++11 -I/home/antoine/Documents/project_c_sinoquet/include/boost_1_68_0
